baseURL: https://gugafer.github.io/
languageCode: en-us
title: Gustavo gugafer
theme: hugo-PaperMod

pagination:
  pagerSize: 10 # âœ… formato correto para Hugo v0.128+

taxonomies:
  category: categories
  tag: tags

outputs:
  home:
    - HTML
    - RSS
    - JSON
    - Sitemap

params:
  env: production
  title: Gustavo gugafer
  description: Cloud & DevOps Engineer | AWS | Azure | Automation | Blog & Personal Page
  keywords:
    - Cloud
    - DevOps
    - Hugo
    - PaperMod
    - Blog
    - Tecnologia
  author: Gustavo gugafer
  DateFormat: January 02, 2006 # âœ… Formato de data americano
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  defaultTheme: auto
  ShowToc: true
  disableThemeToggle: false

  homeInfoParams:
    Title: Hello there, My name is Gustavo ðŸ‘‹
    Content: |
      Sou um engenheiro de Cloud e DevOps com experiÃªncia em projetos multi-cloud, automaÃ§Ã£o, infraestrutura como cÃ³digo (IaC) e seguranÃ§a cibernÃ©tica.   Engenheiro de Cloud e DevOps. Aqui compartilho ideias, soluÃ§Ãµes e aprendizados.

  assets:
    favicon: images/favicon.ico

  analytics:
    google:
      SiteVerificationTag: G-Y08HKQ19T0

  socialIcons:
    - name: github
      url: https://github.com/gugafer
    - name: linkedin
      url: https://www.linkedin.com/in/gugafer/

menu:
  main:
    - name: Blog
      url: /posts/
      weight: 1
    - name: About
      url: /about/
      weight: 2
    - name: Tags
      url: /tags/
      weight: 3